### ISSUE TITLE
[Question] In which step of development is this game ?

### ISSUE THREAD

**Issue by AdrienTorris** [jesta88/Annihilation#1]
Hi

In which step of development is this game ? I tried to launch it but I have just a black console screen. Is it normal ?

**Comment by jesta88** [comment]
There's nothing to see yet. Right now I'm still writing the C# bindings for Vulkan, Wwise and OpenGEX. Full development will begin in February.

I'll update the readme soon.

**Comment by AdrienTorris** [comment]
Ok thank you. Good continuation :)
